version: '3'

services:
  name-node:
    image: ubuntu-hadoop-namenode:hadoop-3.0.0
    networks:
      - bigdata
    volumes:
      - hadoop-data-3.0.0:/var/hadoop
    environment:
      - CLUSTER_NAME=bigdata
    env_file:
      - hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: bigdata
        traefik.port: 9870

  data-node:
    image: ubuntu-hadoop-datanode:hadoop-3.0.0
    networks:
      - bigdata
    volumes:
      - hadoop-data-3.0.0:/var/hadoop
    env_file:
      - hadoop.env
    environment:
      SERVICE_PRECONDITION: "name-node:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata
        traefik.port: 9864
    depends_on:
      - name-node

  resource-manager:
    image: ubuntu-hadoop-resource-manager:hadoop-3.0.0
    networks:
      - bigdata
    environment:
      SERVICE_PRECONDITION: "name-node:9870 data-node:9864"
    env_file:
      - hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: bigdata
        traefik.port: 8031
    healthcheck:
      disable: true
    depends_on:
      - name-node
      - data-node

  node-manager:
    image: ubuntu-hadoop-node-manager-spark-shuffle:hadoop-3.0.0-hive-2.3.7-spark-3.0.0
    networks:
      - bigdata
    environment:
      SERVICE_PRECONDITION: "name-node:9870 data-node:9864 resource-manager:8031"
    env_file:
      - hadoop.env
      - hadoop.spark-shuffle.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: bigdata
        traefik.port: 8040
    depends_on:
      - name-node
      - data-node
      - resource-manager

  hadoop-history-server:
    image: ubuntu-hadoop-history-server:hadoop-3.0.0
    networks:
      - bigdata
    volumes:
      - hadoop-data-3.0.0:/var/hadoop
    environment:
      SERVICE_PRECONDITION: "name-node:9870 data-node:9864 resource-manager:8031"
    env_file:
      - hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: bigdata
        traefik.port: 10200
    depends_on:
      - name-node
      - data-node
      - resource-manager

  hive-metastore-mysql:
    image: ubuntu-hive-metastore-mysql:5.7
    networks:
      - bigdata
    volumes:
      - mysql-data-3.0.0:/var/mysql
    ports:
      - 3306:3306

  hive-metastore:
    image: ubuntu-hadoop-hive:1.2.1-mysql
    networks:
      - bigdata
    env_file:
      - hadoop.env
    command: /root/start_hive_metastore.sh
    environment:
      SERVICE_PRECONDITION: "name-node:9870 data-node:9864 hive-metastore-mysql:3306"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-mysql

  hive-server:
    image: ubuntu-hadoop-hive:1.2.1-mysql
    networks:
      - bigdata
    env_file:
      - hadoop.env
    command: /root/start_hive_server.sh
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:mysql://hive-metastore-mysql/hive"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore-mysql
      - hive-metastore

volumes:
  mysql-data-3.0.0:
  hadoop-data-3.0.0:

networks:
  bigdata: